config/routes.rb
ProjetoIntegracao::Application.routes.draw do
  root to: "home#index"
  resources :rents
  resources :clients
  resources :vehicles

end

app/models/rent.rb
class Rent
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short

  # after_create { assign_role }
  after_create :handle_vehicles
  
  belongs_to :client
  embeds_one :down_payment
  has_many :uses

  # delete from params uses with no vehicles
  accepts_nested_attributes_for :uses,
    reject_if: ->(use) { use[:vehicle_id].blank? unless use[:_destroy] }

  field :start_date, type: Date, default: -> { Date.today }
  field :paid_at, type: Date
    
  def vehicles
    Vehicle.in(id: uses.map(&:vehicle_id))
  end

  private

  def handle_vehicles
    base_value_sum = 0.0
    uses.each do |u|
      v = u.vehicle
      # assign rented status to vehicle
      v.update_attribute(:status, "rented")
      # store base_value of vehicle at the moment the rent has taken place
      u.update_attribute(:base_value, v.base_value)
      base_value_sum += v.base_value
    end

    # set down_payment value
    down_payment = DownPayment.new(value: base_value_sum)
    update_attribute(:down_payment, down_payment)
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]

  # GET /rents
  # GET /rents.json
  def index
    @rents = Rent.all
    @client = Client.new
  end

  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    # select's collection
    @vehicles = Vehicle.where(status: "available")

    @rent = Rent.new
    5.times { @rent.uses.build.build_vehicle }

    # New rent btn sends cpf param
    if params[:client]
      cpf = params[:client][:cpf]
    else # Error from #create sends client_id param
      cpf = Client.find(params[:client_id]).cpf
    end
    unless cpf.nil?
      begin
        @rent.client = Client.find_by(cpf: cpf)
      rescue => e
        render :text => "Não existe cliente com o cpf #{cpf.blank? ? 'vazio' : cpf}", :status => 403 
      end
    end
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new(rent_params)
    vehicle_ids = @rent.uses.map(&:vehicle_id)
    # todo: custom validator desconsiderando os marked_to_delete
    if vehicle_ids.length == vehicle_ids.uniq.length # to check length is faster
      respond_to do |format|
        if @rent.save
          format.html { redirect_to @rent, notice: 'Locação salva com sucesso.' }
          format.json { render action: 'show', status: :created, location: @rent }
        else
          byebug
          format.html { render action: 'new' }
          format.json { render json: @rent.errors, status: :unprocessable_entity }
        end
      end
    else
      # now is to make it work with render (same request)
      flash.now[:error] = "O mesmo veículo foi selecionado mais de uma vez."
      # select's collection
      @vehicles = Vehicle.where(status: "available")
      rent_length = @rent.uses.length
      (5 - rent_length).times { @rent.uses.build.build_vehicle }
      render action: "new"
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_params
      params.require(:rent).permit :start_date,
        :client_id,
        uses_attributes: [
          :vehicle_id,
          :return_date
        ]
    end
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_client_cpf_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= simple_form_for @client, url: new_rent_path, method: "GET", defaults: form_defaults do |f| %>
      <%= f.error_notification %>

      <div class='form-inputs'>
        <%= f.input :cpf %>
      </div>

      <div class='form-actions pull-right'>
        <%= f.button :submit, 'Vincular CPF', class: 'btn-primary' %>
      </div>
    <% end %> 
  </div>
</div>

app/views/rents/_form.html.erb
<%= simple_form_for @rent, defaults: form_defaults do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <span class="no-input"><strong>Cliente:</strong> <%= @rent.client.name %></span>
    <%= f.hidden_field :client_id, value: @rent.client.id %>
    <%# input_html: { value: (l @rent.start_date), id: "rent-start-date-input" } %>
    <%= f.input :start_date, as: :date_picker %>

    <div id="vehicle-container">
      <%= f.fields_for :uses, @rent.uses, defaults: form_defaults do |u, index| %>
        <div class="vehicle-panel">
          <%#= u.fields_for :vehicle, u.object.vehicle, defaults: form_defaults do |v| %>
            <%#= v.input :id, collection: @vehicles, label_method: :full_name,
                        label: "Veículo #{u.index + 1}" %>
          <%# end %>
          <%= u.input :vehicle_id, collection: @vehicles, label_method: :full_name,
                      label: "Veículo #{u.index + 1}" %>
          <%= u.input :return_date, as: :date_picker %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-actions pull-right">
    <%= f.button :submit, "#{f.object.new_record? ? 'Criar' : 'Editar'}", class: "btn-primary" %>
  </div>
<% end %> 

<%#= simple_form_for @rent, defaults: form_defaults do |f| %>
    <%# @rent.vehicles = [Vehicle.new, Vehicle.new] %>
    <%# @rent.vehicles.each do |vehicle| %>
      <%#= f.fields_for :vehicles, vehicle, defaults: form_defaults do |v| %>
        <%# v.index %>
        <%#= v.input :id, collection: @vehicles %>
        <%#= v.input :id, collection: @vehicles, as: :grouped_select, group_method: "model.manufacturer.name" %>
      <%# end %> 
    <%# end %> 
    <!-- ou -->
    <%#= f.fields_for :vehicles, @rent.vehicles, defaults: form_defaults do |v| %>
      <%# v.index %> 
      <%#= v.input :id, collection: @vehicles, as: :grouped_select, group_method: "model.manufacturer.name" %>
    <%# end %>
<%# end %> 

app/views/rents/edit.html.erb
<h1>Editing rent</h1>

<%= render 'form' %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

app/views/rents/index.html.erb
<div class="page-header">
  <h3>
    Gerenciar locações
    <span class="pull-right">
      <%= button_tag 'Nova Locação', id:"rooba", class: "btn btn-primary", title: "Digite CPF do Cliente", data: { content: (render "client_cpf_form").gsub('“', "'")  } %>
    </span>
  </h3>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Data de Cadastro</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.client.name %></td>
        <td><%= rent.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="text-right">
          <%= link_to 'Editar', edit_rent_path(rent), class: "btn btn-default" %>
          <%= link_to 'Remover', rent, class: "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rents/new.html.erb
<div class="page-header">
  <h3>
    Nova locação
    <span class="pull-right">
      <%= link_to 'Voltar', rents_path, class: "btn btn-default" %>
    </span>
  </h3>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rent_path(@rent) %> |
<%= link_to 'Back', rents_path %>