config/routes.rb
ProjetoIntegracao::Application.routes.draw do
  root to: "home#index"
  resources :rents
  resources :clients
  resources :vehicles

end

app/models/client.rb
class Client
  include Mongoid::Document

  has_many :rents

  field :cpf, type: String
  field :name, type: String
  field :email, type: String
  field :phone, type: String
  field :address, type: String
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Cliente criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_path, notice: 'Cliente editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params[:client].permit(:cpf, :name, :email, :phone, :address)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client, defaults: form_defaults do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :cpf %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :address %>
  </div>

  <div class="form-actions pull-right">
    <%= f.button :submit, "#{f.object.new_record? ? 'Criar' : 'Editar'}", class: "btn-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="page-header">
  <h3>
    Editar cliente
    <span class="pull-right">
      <%= link_to 'Voltar', clients_path, class: "btn btn-default" %>
    </span>
  </h3>
</div>

<div class="row">
  <div class="col-lg-4">
    <%= render 'form' %>
  </div>
</div>

app/views/clients/index.html.erb
<div class="page-header">
  <h3>
    Gerenciar clientes
    <span class="pull-right">
      <%= link_to 'Novo Cliente', new_client_path, class: "btn btn-primary" %>
    </span>
  </h3>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.cpf %></td>
        <td class="text-right">
          <%= link_to 'Nova Locação', new_rent_path(client: { cpf: client.cpf }), class: "btn btn-primary" %>
          <%= link_to 'Gerenciar Locações', client, class: "btn btn-default" %>
          <%= link_to 'Editar', edit_client_path(client), class: "btn btn-default" %>
          <%= link_to 'Remover', client, class: "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<div class="page-header">
  <h3>
    Novo cliente
    <span class="pull-right">
      <%= link_to 'Voltar', clients_path, class: "btn btn-default" %>
    </span>
  </h3>
</div>

<div class="row">
  <div class="col-lg-4">
    <%= render 'form' %>
  </div>
</div>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>