config/routes.rb
ProjetoIntegracao::Application.routes.draw do
  root to: "home#index"
  resources :rents
  resources :clients
  resources :vehicles

end

app/models/vehicle.rb
class Vehicle
  include Mongoid::Document

  belongs_to :model
  has_many :uses

  accepts_nested_attributes_for :model

  field :year, type: Integer
  field :plate, type: String
  field :base_value, type: Float
  field :status, type: String, default: "available"

  EDITABLE_STATUS = [ "available", "fixing" ]

  def rents
    Rent.in(id: uses.map(&:rent_id))
  end

  def status(raw = true)
    raw ? read_attribute(:status) : serialize_status(read_attribute(:status))
  end

  def full_name
    "#{plate} - #{name}"
  end

  def name
    "#{model.manufacturer.name} #{model.name}"
  end

  private
    def serialize_status status
      case status
        when "available"
          add_color status, "success"
        when "fixing"
          add_color status, "warning"
        when "rented"
          add_color status, "danger"
        else
          add_color "no_info", "default"
      end
    end

    def add_color status, klass
      "<span class='#{klass}'><strong>#{I18n.t(status).capitalize}</strong></span>".html_safe
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index #sort_by {|x|[x.rating,x.name,-x.people.size]}, - is desc
    @vehicles = Vehicle.all.sort_by! { |v| [v.model.manufacturer.name.downcase, v.model.name.downcase] }
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    @vehicle.build_model
    # @manufacturers = Manufacturer.all.sort_by(&:name)
    @manufacturers = Manufacturer.order_by(name: :asc)
    @possible_models = Manufacturer.possible_models @manufacturers.to_a
  end

  # GET /vehicles/1/edit
  def edit
    @manufacturers = Manufacturer.order_by(name: :asc)
    @possible_models = Manufacturer.possible_models @manufacturers.to_a
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicles_path, notice: 'Veículo criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @vehicle }
      else
        format.html { render action: 'new' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicles_path, notice: 'Veículo editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit :year, :plate, :base_value, :status,
        :model_id,
        manufacturer_attributes: [:id]
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= simple_form_for @vehicle, defaults: form_defaults do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.fields_for :model, @vehicle.model, defaults: form_defaults do |mo| %>
      <%= mo.input :manufacturer_id, collection: @manufacturers, selected: @vehicle.model.manufacturer_id, include_blank: true %>
    <% end %>

    <%= f.input :model_id, collection: [""], input_html: { disabled: true, data: { "possible-models" => @possible_models, selected: (@vehicle.new_record? ? "" : @vehicle.model_id.to_s) } } %>
    
    <%= f.input :year, collection: ((1.year.from_now.year - 21)..(1.year.from_now.year)).to_a.reverse %>
    <%= f.input :plate %>
    <%= f.input :base_value, as: :float %>

    <%= render partial: "status", locals: { f: f } unless @vehicle.new_record? %>
    <%#= render partial: "status", locals: { vehicle: @vehicle } unless @vehicle.new_record? %>
  </div>

  <div class="form-actions pull-right">
    <%= f.button :submit, "#{f.object.new_record? ? 'Criar' : 'Editar'}", class: "btn-primary" %>
  </div>
<% end %>

app/views/vehicles/_status.html.erb
<% if @vehicle.status == "rented" %>
  <strong>Status:</strong> <%= @vehicle.status false %>
<% else %>
  <%= f.input :status, collection: t(Vehicle::EDITABLE_STATUS), include_blank: false, value_method: ->(el) { t el, locale: :en } %>
<% end%>

app/views/vehicles/edit.html.erb
<div class="page-header">
  <h3>
    Editar veículo
    <span class="pull-right">
      <%= link_to 'Voltar', vehicles_path, class: "btn btn-default" %>
    </span>
  </h3>
</div>

<div class="row">
  <div class="col-lg-4">
    <%= render 'form' %>
  </div>
</div>

app/views/vehicles/index.html.erb
<div class="page-header">
  <h3>
    Gerenciar veículos
    <span class="pull-right">
      <%= link_to 'Novo Veículo', new_vehicle_path, class: "btn btn-primary" %>
    </span>
  </h3>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Disponibilidade</th>
      <th>Modelo</th>
      <th>Placa</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><strong><%= vehicle.status(false) %></strong></td>
        <td><%= "#{vehicle.model.manufacturer.name} #{vehicle.model.name}" %></td>
        <td><%= vehicle.plate %></td>
        <td class="text-right">
          <%= link_to 'Editar', edit_vehicle_path(vehicle), class: "btn btn-default" %>
          <%= link_to 'Remover', vehicle, class: "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vehicles/new.html.erb
<div class="page-header">
  <h3>
    Novo veículo
    <span class="pull-right">
      <%= link_to 'Voltar', vehicles_path, class: "btn btn-default" %>
    </span>
  </h3>
</div>

<div class="row">
  <div class="col-lg-4">
    <%= render 'form' %>
  </div>
</div>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>